### ISSUE TITLE
extractTransactionIdFromAppReceipt not finding transaction ID if receipt has an empty in_app array

### ISSUE THREAD

**Issue by mcastany** [apple/app-store-server-library-node#10]
I found a receipt that has an empty in_app, but it has `latest_receipt_info`. I think the method should fallback to that array if there' no in_app

**Comment by alexanderjordanbaker** [comment]
latest_receipt_info is from Verify Receipt when a password is provided, there is no latest_receipt_info actually contained in the receipt.
