### ISSUE TITLE
server endpoints not support ipv6?

### ISSUE THREAD

**Issue by c3qo** [apple/app-store-server-library-node#118]
Wondering if my test was correct, seems the Sandbox and Production endpoints are not reachable from an ipv6-only network, because the two endpoints have no DNS for ipv6. I have to use proxy to forward the requests.

```sh
> ping6 apple.com
16 bytes from 2620:149:af0::10, icmp_seq=0 hlim=58 time=174.733 ms

> ping6 api.storekit-sandbox.itunes.apple.com
ping6: getaddrinfo -- nodename nor servname provided, or not known
```

Thanks

**Comment by alexanderjordanbaker** [comment]
Hello! At this time IPv6 is not supported on the App Store Server API
