### ISSUE TITLE
getting wrong transaction id in extractTransactionIdFromAppReceipt method

### ISSUE THREAD

**Issue by sailingwithsandeep** [apple/app-store-server-library-node#128]
This is very strange. whenever i got the transaction from client i am getting different raw receipt & after calling extractTransactionIdFromAppReceipt i am getting same transaction id every time.

```
        const applePayload = JSON.parse(req.body.payload);
        console.log(`😈🤨 very bad! ~ acknowledgeApplePurchase: ~ req.body.payload:`, req.body.payload);
        const receiptUtil = new ReceiptUtility();
        const transactionId = receiptUtil.extractTransactionIdFromAppReceipt(applePayload.Payload);
        console.log(`😈🤨 very bad! ~ acknowledgeApplePurchase: ~ transactionId:`, transactionId);
        if (!transactionId) return;

        const response = await appleClient.getTransactionInfo(transactionId);
        if (!response?.signedTransactionInfo) return;

        const receipt = new SignedDataVerifier(certs, true, environment, bundleId);

        const payload = await receipt.verifyAndDecodeTransaction(response.signedTransactionInfo);
        console.log(`😈🤨 very bad! ~ acknowledgeApplePurchase: ~ response.signedTransactionInfo:`, response.signedTransactionInfo);
        console.log(`😈🤨 very bad! ~ acknowledgeApplePurchase: ~ payload:`, payload);

```

is something wrong here??

**Comment by alexanderjordanbaker** [comment]
Extract transaction id from app receipt extracts only one of the transaction ids, so that you can then call Get Transaction History and get the full history for the user, as the example in the README does.

**Comment by alexanderjordanbaker** [comment]
You are calling Get Transaction Info, which only gets on transaction, which is the incorrect endpoint to use here

**Comment by sailingwithsandeep** [comment]
@alexanderjordanbaker 
```
receiptUtil.extractTransactionIdFromAppReceipt
```
this method is giving me same transaction id from signed payload

**Comment by sailingwithsandeep** [comment]
> Extract transaction id from app receipt extracts only one of the transaction ids, so that you can then call Get Transaction History and get the full history for the user, as the example in the README does.

i am verifying iap receipt that for that i need only receipt per call

**Comment by Miguelyrax** [comment]
Same problem here

**Comment by alexanderjordanbaker** [comment]
@sailingwithsandeep The App Receipt contains all transactions for a user. The only purpose of the extractTransactionIdFromAppReceipt method is to then pass that identifier to Get Transaction History as shown in the README. The transaction id you extract is a random transaction id from the user it is not the latest one

**Comment by sailingwithsandeep** [comment]
@alexanderjordanbaker  So, what's best way to get latest transaction id?

**Comment by alexanderjordanbaker** [comment]
Call Get Transaction History which will returns all the transactions, including the latest.

**Comment by alexanderjordanbaker** [comment]
Closing this issue, please open a new issue for additional assistance
