### ISSUE TITLE
Not compatible with Deno, Bun

### ISSUE THREAD

**Issue by c128128** [apple/app-store-server-library-node#173]
Thank you for your work. However, at the moment, this library is not compatible with Deno or Bun. Are there any plans to make it compatible?

**Comment by alexanderjordanbaker** [comment]
@c128128 Could you please share errors or incompatibility you are seeing with Bun, for example?

**Comment by alexanderjordanbaker** [comment]
Closing for no response, please reopen if further discussion is required
