### ISSUE TITLE
loadRootCAs()  part.. 

### ISSUE THREAD

**Issue by YoungrakSon** [apple/app-store-server-library-node#18]
I've downloaded Apple Root CA from here https://www.apple.com/certificateauthority/

but I have no idea how I can import that file and call 
const verifier = new SignedDataVerifier(appleRootCAs, enableOnlineChecks, environment, bundleId)

I'm keep getting errors like 
Error: Failed to load function definition from source: Failed to generate manifest from function source: TypeError: Cannot read properties of undefined (reading 'map')

How can I load appleRootCAs and feed it to SignedDataVerifier?

**Comment by YoungrakSon** [comment]
const REAL_APPLE_ROOT_BASE64_ENCODED = `
MIICQzCCAcmgAwIBAgIILcX8iNLFS5UwCgYIKoZIzj0EAwMwZzEbMB
kGA1UEAwwSQXBwbGUgUm9vdCBDQSAtIEczMSYwJAYDVQQLDB1BcHBs
ZSBDZXJ0aWZpY2F0aW9uIEF1dGhvcml0eTETMBEGA1UECgwKQXBwbG
UgSW5jLjELMAkGA1UEBhMCVVMwHhcNMTQwNDMwMTgxOTA2WhcNMzkw
NDMwMTgxOTA2WjBnMRswGQYDVQQDDBJBcHBsZSBSb290IENBIC0gRz
MxJjAkBgNVBAsMHUFwcGxlIENlcnRpZmljYXRpb24gQXV0aG9yaXR5
MRMwEQYDVQQKDApBcHBsZSBJbmMuMQswCQYDVQQGEwJVUzB2MBAGBy
qGSM49AgEGBSuBBAAiA2IABJjpLz1AcqTtkyJygRMc3RCV8cWjTnHc
FBbZDuWmBSp3ZHtfTjjTuxxEtX/1H7YyYl3J6YRbTzBPEVoA/VhYDK
X1DyxNB0cTddqXl5dvMVztK517IDvYuVTZXpmkOlEKMaNCMEAwHQYD
VR0OBBYEFLuw3qFYM4iapIqZ3r6966/ayySrMA8GA1UdEwEB/wQFMA
MBAf8wDgYDVR0PAQH/BAQDAgEGMAoGCCqGSM49BAMDA2gAMGUCMQCD
6cHEFl4aXTQY2e3v9GwOAEZLuN+yRhHFD/3meoyhpmvOwgPUnPWTxn
S4at+qIxUCMG1mihDK1A3UT82NQz60imOlM27jbdoXt2QfyFMm+Yhi
dDkLF1vLUagM6BgD56KyKA==`;

const verifier = new SignedDataVerifier([Buffer.from(
    REAL_APPLE_ROOT_BASE64_ENCODED, "base64")], enableOnlineChecks,
environment, bundleId);


I couldn't read the Apple Root CA .cer file,  so I just copied some lines from the package source code and solved it haha.. it would be great If I can get to know better ways.

**Comment by dminglv** [comment]
Apple asks not to hardcode certificates in the code.

In my case, I load the certificates every time when initializing the module in NestJS at the start of the application.


```
@Injectable()
export class AppstoreService implements OnModuleInit {
  private appleRootCA: Buffer[];
  
  constructor(private readonly configService: ConfigService) {}
  
  async onModuleInit() {
    this.appleRootCA = await this.readAppleCerts();
    
  }
  
  private async downloadAppleCert(url: string): Promise<Buffer> {
    try {
      const response = await axios.get(url, { responseType: 'arraybuffer' });
      return Buffer.from(response.data);
    } catch (error) {
      this.logger.error(`Error downloading ${url}:`, error);
      throw error;
    }
  }

  private async readAppleCerts(): Promise<Buffer[]> {
    try {
      const urls = [
        'https://www.apple.com/appleca/AppleIncRootCertificate.cer',
        'https://www.apple.com/certificateauthority/AppleComputerRootCertificate.cer',
        'https://www.apple.com/certificateauthority/AppleRootCA-G2.cer',
        'https://www.apple.com/certificateauthority/AppleRootCA-G3.cer',
      ];

      return await Promise.all(urls.map((url) => this.downloadAppleCert(url)));
    } catch (error) {
      this.logger.error('Error in downloading Apple certificates:', error);
      throw error;
    }
  }

**Comment by alexanderjordanbaker** [comment]
We recommend you store the appropriative root CAs as variables your code may load. However, the code snippet you shared, @YoungrakSon is correct if the value was stored in Base64 encoded form, whether embedded in code or as a loaded variable. I would not recommend loading the values fresh each time from Apple's website, but instead download these files and store them as part of your configuration, whatever that looks like for your deployment process. Because these are Apple Root CAs, they should never change and generally added to very infrequently (on the order of a decade). Our most recent root, G3, expires on Apr 30 18:19:06 2039 GMT.

**Comment by alexanderjordanbaker** [comment]
The root CAs can be downloaded under the Apple Root Certificates header on https://www.apple.com/certificateauthority/
