### ISSUE TITLE
error code: 504

### ISSUE THREAD

**Issue by hengkydev** [apple/app-store-server-library-node#201]
everytime I try to get the transaction using `getTransactionInfo` there's a chance that I got `error code: 504`

Im not sure how to reproduce this cause sometimes is work sometimes is not with the same `transactionId`

I was wondering are this related to Rate Limit as well, since im using cronjob for fallback handler for renewal 
but the error not saying that at all , 
im refer to this [doc](https://developer.apple.com/documentation/appstoreserverapi/ratelimitexceedederror/) 

Also im check the possible http return code from [here](https://developer.apple.com/documentation/appstoreconnectapi/interpreting_and_handling_errors/about_the_http_status_code/)
but Im not found any `504`

the `504` always return when the request are exceed 60s (1 min) , I was suspect that related to my code limiting the timeout but turned its not 
![test](https://github.com/user-attachments/assets/621c8ddf-87b0-4711-84a0-037df17209c5)

its only happen when I get the transaction but its random, sometimes working sometimes not (mostly working)
![Screenshot at Sep 10 10-25-47](https://github.com/user-attachments/assets/02d90f80-97e4-4ff3-8d11-2042c3e5d6fa)

this are my simple code , just FYI this already used in production and we got some issue where some of the users are not getting their subscription correctly

```ts
/**
   * Gets apple tansaction by id
   * @param {string} transactionId
   * @returns {Promise<TransactionInfoResponse> }
   */
  async getTransactionById(
    transactionId: string,
  ): Promise<TransactionInfoResponse> {
    try {
      const transaction = await this.client.getTransactionInfo(transactionId);

      const result = await this.verifier.verifyAndDecodeTransaction(
        transaction.signedTransactionInfo,
      );

      console.log('result', result);

      return transaction;
    } catch (error) {
      Logger.log(
        `Error getting the apple transaction: [${transactionId}]: ${error}`,
      );
      throw new ValidationException(
        `Error getting the apple transaction: ${error}`,
      );
    }
  }
  ```

**Comment by alexanderjordanbaker** [comment]
@hengkydev Are you still experiencing this issue?
