### ISSUE TITLE
        verifyAndDecodeAppTransaction got INVALID_ENVIRONMENT error

### ISSUE THREAD

**Issue by Lshane97** [apple/app-store-server-library-node#218]
I was trying to decode a signedTransaction string from Sandbox test, but got new VerificationException(VerificationStatus.INVALID_ENVIRONMENT) error.

So i logged before this line and got decoded json
```
{
  transactionId: '2000000796570433',
  originalTransactionId: '2000000796570433',
  bundleId: '',
  productId: '',
  purchaseDate: 1733385570000,
  originalPurchaseDate: 1733385570000,
  quantity: 1,
  type: 'Non-Consumable',
  deviceVerification: '',
  deviceVerificationNonce: '',
  inAppOwnershipType: 'PURCHASED',
  signedDate: 1733385575204,
  environment: 'Sandbox',
  transactionReason: 'PURCHASE',
  storefront: 'CHN',
  storefrontId: '143465',
  price: 18000,
  currency: 'CNY'
}
```

and there is no `receiptType` key
so maybe this line should be  `const environment = decodedAppTransaction.environment` ? 

https://github.com/apple/app-store-server-library-node/blob/5f344871b21f3882611c5cf791b0c0ca7428d56f/jws_verification.ts#L154

**Comment by thedewpoint** [comment]
@Lshane97 I'm getting this same issue. How did you get around it?

**Comment by Lshane97** [comment]
> @Lshane97 I'm getting this same issue. How did you get around it?

@thedewpoint try use `verifyAndDecodeTransaction`

**Comment by thedewpoint** [comment]
> > @Lshane97 I'm getting this same issue. How did you get around it?
> 
> @thedewpoint try use `verifyAndDecodeTransaction`

thank you! that worked
