### ISSUE TITLE
Is available/recomended to use lib in Prod env?

### ISSUE THREAD

**Issue by sebaber** [apple/app-store-server-library-node#24]
First of all thanks so much for this library, the documentation plus the video is excelent to understand how it works.

I read the documentation that is not recomended to use it in Prod env because is BETA atm because of some things can be changing.

Ignoring this risk that mention, can we use it in Prod env or there is another problem for that?

If we can not be use in it yet, is there an ETA of the release? and what other npm lib recommend instead?

Sorry if this is not the media to put that suggestion and, again, thanks for that awesome lib!

**Comment by alexanderjordanbaker** [comment]
Hello @sebaber . Generally using an API client in production will work. The key place to watch until beta is complete is using this to verify the signatures on signed data like transactions.

**Comment by aslamanver** [comment]
> Hello @sebaber . Generally using an API client in production will work. The key place to watch until beta is complete is using this to verify the signatures on signed data like transactions.

HI We get error SignedDataVerification

**Comment by sebaber** [comment]
Thanks for the info. At the moment, we use this API at production and did not have any issue, so i will close this issue.
