### ISSUE TITLE
Why query the transaction details interface with different transaction_id and get the same transaction?

### ISSUE THREAD

**Issue by code-for-money** [apple/app-store-server-library-node#28]
hi
Question:
I have two transaction IDs, calling the inApps/v1/transactions/{transaction_id} endpoint,
What seems to be the same transaction is obtained, but the transaction ID is different.
![image](https://github.com/apple/app-store-server-library-node/assets/141889079/3b140e83-9892-4cc1-91f7-22acedeec770)
![image](https://github.com/apple/app-store-server-library-node/assets/141889079/733c62b5-75a3-454b-a52a-6e13609e6ae4)

You can see that the above two transaction IDs are different, but webOrderLineItemId and originalTransactionId are the same. I think it should be the same transaction, right? Why does this problem occur?

**Comment by alexanderjordanbaker** [comment]
This can occur when a transaction is regranted or when the same transaction is accessed on multiple devices in Original Storekit, where multiple transaction ids can refer to the same purchase.

**Comment by code-for-money** [comment]
> This can occur when a transaction is regranted or when the same transaction is accessed on multiple devices in Original Storekit, where multiple transaction ids can refer to the same purchase.

thinks! What does it mean  transaction is regranted ? under what circumstances would this be triggered?

**Comment by alexanderjordanbaker** [comment]
https://developer.apple.com/documentation/storekit/in-app_purchase/original_api_for_in-app_purchase/restoring_purchased_products

Specifically restoreCompletedTransactions

**Comment by code-for-money** [comment]
> https://developer.apple.com/documentation/storekit/in-app_purchase/original_api_for_in-app_purchase/restoring_purchased_products
> 
> Specifically restoreCompletedTransactions

Thanks
