### ISSUE TITLE
Getting 404 error while calling methong getTransactionInfo (APIError Code: 4040010)

### ISSUE THREAD

**Issue by abdullahjavaid86** [apple/app-store-server-library-node#31]
I am trying to fetch transaction details and constantly getting a 404 error.

When I try to fetch details for older transactions, it works.

If it might have something to do with reading the p8 file, can you explain what `readFile(filePath)` function does?

I am currently passing the key as 
`const privateKeyPath = "/SubscriptionKey.p8";`
`const privateKey = fs.readFileSync(__dirname + privateKeyPath, "utf8");`
 `const serverApi2 = new AppStoreServerAPIClient(
    privateKey,
    KEY_ID,
    ISSUER_ID,
    bundleId,
    Environment.PRODUCTION
  );
`

Stuck on this error for quite a while now.

**Comment by alexanderjordanbaker** [comment]
If it works on some transactions, it is not a problem with reading the file. Is this Sandbox or Production?

**Comment by abdullahjavaid86** [comment]
It is on Production.

**Comment by alexanderjordanbaker** [comment]
@abdullahjavaid86 Without more information, I am unable to diagnose what might be happening. As this seems to be an issue server-side, not as much with the library itself, please file a ticket in Feedback Assistant (http://feedbackassistant.apple.com), include the transaction id(s), time of request, appAppleId, and any other information related to the issue.

**Comment by abdullahjavaid86** [comment]
I have already done that, thanks for your response.
