### ISSUE TITLE
When will this library be updated to include the additions in App Store Notification 2.9

### ISSUE THREAD

**Issue by azimlumos** [apple/app-store-server-library-node#35]
Hi, about a week ago Apple released App Store Server Notifications v 2.9:

https://developer.apple.com/documentation/appstoreservernotifications/jwstransactiondecodedpayload?changes=latest_minor

This includes having the price and currency in the JWSTransactionDecodedPayload. I was wondering when we can expect this library to be updated to incorporate these changes. I see you already have a commit:

https://github.com/apple/app-store-server-library-node/commit/7db72275713fbfca8a65e731255706ab41479c5d

but just wanted to know when you will be making a release for it.

**Comment by yhostc** [comment]
Also very much looking forward to it

**Comment by yhostc** [comment]
This problem has been solved #39
