### ISSUE TITLE
It is recommended to update the version to npm ​

### ISSUE THREAD

**Issue by yhostc** [apple/app-store-server-library-node#39]
[Question]
Property 'currency' does not exist on type 'JWSTransactionDecodedPayload'.ts(2339)

[Track]
- I use the lastest version for `@apple/app-store-server-library`, `v0.1.1
- But the latest code is correct
https://github.com/apple/app-store-server-library-node/blob/4efa412a46ce83e6fac8c785b143f5decaa99db0/models/JWSTransactionDecodedPayload.ts#L186C10-L186C10

[Solution]
It is recommended to update the version to npm ​

**Comment by alexanderjordanbaker** [comment]
Closed by #41
