### ISSUE TITLE
App Attest receipt parsing and validation

### ISSUE THREAD

**Issue by DePasqualeOrg** [apple/app-store-server-library-node#52]
I'm trying to parse and validate receipts as part of attestations sent by my app to my server. I see that the current receipt utility doesn't have this functionality, but would this be within the scope of this project?

See also: https://github.com/tamtamchik/app-store-receipt-parser/issues/2#issuecomment-1863421124

**Comment by alexanderjordanbaker** [comment]
Hello @DePasqualeOrg we do offer verification of signed data with the SignedDataVerifier. To allow developers to support clients that haven’t yet updated to StoreKit 2, we have the ReceiptUtility class which allows you to extract a transaction id from a legacy receipt, which you can then call the App Store Server API to get a signed transaction

**Comment by DePasqualeOrg** [comment]
Thanks. I can't tell from the documentation or the source code how to use SignedDataVerifier to parse and validate App Attest receipts and get the fraud metric, for example.

**Comment by alexanderjordanbaker** [comment]
Can you please link to the App Attest receipt documentation

**Comment by DePasqualeOrg** [comment]
I'm referring to the documentation of this project. I don't see any methods in SignedDataVerifier that look like they would accept an App Attest receipt returned from the endpoint discussed here: https://developer.apple.com/documentation/devicecheck/assessing_fraud_risk

**Comment by alexanderjordanbaker** [comment]
As at look at this, curious, are you saying you are passing Attest receipts to verify receipt currently?

**Comment by DePasqualeOrg** [comment]
No, I haven't tried to use this library yet, because it looks like it isn't meant to parse and validate the receipts I mentioned above. Hence my question as to whether that functionality would be within the scope of the project.

**Comment by alexanderjordanbaker** [comment]
Oh, I see, I saw Verify Receipt in the original link you posted. Yes, these aren’t within the current scope of the project, as these aren’t related to the App Store Server API or App Store Server Notifications.

**Comment by DePasqualeOrg** [comment]
Okay, thanks. I'm glad to see Apple providing reference implementations for server-side stuff, and I hope this will someday extend to App Attest, since I've had a lot of trouble implementing this myself.
