### ISSUE TITLE
How can I identify the environment of the signed notification?

### ISSUE THREAD

**Issue by Kamrul-Hasan-1971** [apple/app-store-server-library-node#55]
To create a SignedDataVerifier, I need to pass the environment.

**Here's one possible approach**:
First, try with the `Production` environment. If there is an exception and the status is `INVALID_ENVIRONMENT = 3`, then try with the `Sandbox` environment.

Is this the recommended approach?

**Comment by alexanderjordanbaker** [comment]
Can you provide a little more context what type of data you are verifying. With notifications, for example, you already know the environment based on which URL the notification was received.

**Comment by Kamrul-Hasan-1971** [comment]
Apologies for the confusion. I mistakenly assumed we were using the same endpoint for both the production and sandbox environments. This led me to consider how to differentiate the environment for signed notifications. 
I appreciate your prompt response. Thanks.

**Comment by Kamrul-Hasan-1971** [comment]
Apologies for the confusion. I mistakenly assumed we were using the same endpoint for both the production and sandbox environments. This led me to consider how to differentiate the environment for signed notifications. 
I appreciate your prompt response. Thanks.
