### ISSUE TITLE
Explanation on the best practices to load root certificates

### ISSUE THREAD

**Issue by ezain701** [apple/app-store-server-library-node#57]
To create a SignedDataVerifier, I need to pass the root certificates.

Here's one possible approach:
I see that apple provides 4 root certificates here : https://www.apple.com/certificateauthority/
I'm thinking of storing them in s3. Would this be a recommended approach?
But then I think what if these are rotated by apple? Would it be better download them dynamically using a network request instead?

**Comment by alexanderjordanbaker** [comment]
Root certificates are not rotated, as they are root CAs. We recommend downloading and storing them in whatever locations works best for your use case. Any cert rotations occurs in the intermediate and leaf certificates, which the library automatically handles by building the entire signing chain back to one of the roots.

**Comment by ezain701** [comment]
@alexanderjordanbaker Thanks for a quick response. Just one quick question. What is the size of these certificates? Do you think they could be stored in environment variables(to avoid latency), or something like AWS Parameter Store/Secrets Manager?

**Comment by alexanderjordanbaker** [comment]
These values are probably a KB each, not large at all. There is nothing secret about them (as public keys) so they could be stored in an env var, or loaded at startup and then stored in memory from that point onwards

**Comment by ezain701** [comment]
@alexanderjordanbaker Thank you
