### ISSUE TITLE
TypeError: Cannot read properties of null (reading 'length') -- while extracting transactionId from receipt

### ISSUE THREAD

**Issue by ezain701** [apple/app-store-server-library-node#59]
When I try to extract transactionId from receipt with the following :
`const transactionId = receiptUtil.extractTransactionIdFromAppReceipt(base64Receipt)`

I get this error : 
```
TypeError: Cannot read properties of null (reading 'length')
    at Tp.extractTransactionIdFromAppReceipt (/node_modules/@apple/app-store-server-library/receipt_utility.ts:42:29)
```

My base64Receipt doesn't start with `MI` though like it's mentioned in docs, it starts with `TU`. Frontend is sending it to me. Could it be the frontend is sending the wrong base64String? Or there might be something else wrong here with the library.

**Comment by alexanderjordanbaker** [comment]
In general an app receipt will always start with MI. I would recommend confirming you are being sent the app receipt

**Comment by alexanderjordanbaker** [comment]
@ezain701 Were you able to resolve your issue?

**Comment by alexanderjordanbaker** [comment]
Closing this issue, if you continue to have issues please reopen or create a new issue
