### ISSUE TITLE
APIException.apiError 4040010 is missing

### ISSUE THREAD

**Issue by nbapps** [apple/app-store-server-library-node#60]
Status `4040010`, which should indicate that `TRANSACTION_ID_NOT_FOUND` is not returned by the service when using the production environment with a Sandbox transaction ID.
The only response is 
```
APIException {
   httpStatusCode: 401,
    apiError: null,
    errorMessage: null
}
```

**Comment by alexanderjordanbaker** [comment]
@nbapps That is expected, since a 401 response is not valid JSON, and so we fall back to just returning the status code. Does your app have a production release yet? Apps without a production release are not authorized to call any production endpoints, which may explain the 401

**Comment by nbapps** [comment]
@alexanderjordanbaker Thanks for your precisions 

No, this is a new application, I'm currently testing everything to do with transaction management on the server and I've noticed this problem.
The documentation clearly states to expect code 4040010 and doesn't mention 401 or any explanation about production release.

That's why I've created this issue

https://developer.apple.com/documentation/appstoreserverapi
```
If you don’t have environment information, follow these steps:
Call the endpoint using the production URL. If the call succeeds, the transaction identifier belongs to the production environment.
If you receive an error code 4040010 [TransactionIdNotFoundError](https://developer.apple.com/documentation/appstoreserverapi/transactionidnotfounderror), call the endpoint using the sandbox environment.
If the call succeeds, the transaction identifier belongs to the sandbox environment. If the call fails with the same error code, the transaction identifier isn’t present in either environment.
```

Nicolas

**Comment by alexanderjordanbaker** [comment]
@nbapps That is true, although that only applies if you don't have environment information, which can always be passed from the app to the server along with the transaction id. Better yet, if you pass the entire JWS (https://developer.apple.com/documentation/storekit/verificationresult/3868429-jwsrepresentation) you can verify directly on the server without needing to call the App Store Server API.

If you have an request related to documentation or behavior of the underlying API, I recommend filing a ticket in Feedback Assistant (http://feedbackassistant.apple.com) which will be routed appropriately

**Comment by nbapps** [comment]
@alexanderjordanbaker Thank you for this information!
I close the issue

Nicolas
