### ISSUE TITLE
High Sev CVE Flag from dependency on `jsrsasign` older than v11

### ISSUE THREAD

**Issue by zackdotcomputer** [apple/app-store-server-library-node#61]
Running an `npm audit` in a project that depends on this package turns up the following "high sev" cve flag:
```
jsrsasign  <11.0.0
Severity: high
Marvin Attack of RSA and RSAOAEP decryption in jsrsasign - https://github.com/advisories/GHSA-rh63-9qcf-83gf
No fix available
node_modules/jsrsasign
  @apple/app-store-server-library  *
  Depends on vulnerable versions of jsrsasign
  node_modules/@apple/app-store-server-library
```

While accepting that many people consider NPM CVEs to be more noise than useful information, managing them is nonetheless often a requirement of compliance to enterprise standards like SOC-2. Because of that and because of the relatively straightforward remediation pathway of updating `jsrsasign` to v11 or newer, I'm raising this issue to request that update be done in this package.

**Comment by alexanderjordanbaker** [comment]
This is resolved in v 1.0.1
