### ISSUE TITLE
[Question] Contributions

### ISSUE THREAD

**Issue by rodrigoborgesdeoliveira** [apple/app-store-server-library-node#7]
Hello 👋, I'm glad to see that Apple is creating this official library to make it easier to integrate with the App Store Server APIs.

I was looking for a contributions guideline or a `CONTRIBUTING.md` file, but couldn't find any. Is this repository open to public contributions?

**Comment by alexanderjordanbaker** [comment]
@rodrigoborgesdeoliveira Thank you for reaching out. We have just added https://github.com/apple/app-store-server-library-node/blob/main/CONTRIBUTING.md, and we are open to public contributions
