### ISSUE TITLE
Missing an example for how to verify an IAP transaction receipt

### ISSUE THREAD

**Issue by eedeebee** [apple/app-store-server-library-node#84]
Either we don't need to do this and we can just look up transaction IDs via this library... wr we could use an example of how to do this with this API.  The docs are also unclear if you can look up transactioninfo for an unfinished transaction - for me so far, it doesn't work.

**Comment by alexanderjordanbaker** [comment]
Hello @eedeebee, can you be a little more specific with what IAP transaction receipt you are referring to, is it a JWSTransaction (https://developer.apple.com/documentation/appstoreserverapi/jwstransaction)? Also, unfinished transactions are visible in the Get Transaction History or Get Transaction Info endpoints in the App Store Server API

**Comment by eedeebee** [comment]
Thanks I'm just learning here  and appreciate help.  My question has morphed a bit as I'm for now just testing against the sandbox and I'd like to use the SignedDataVerifier (essentially offline without talking to the App Store best I can tell) with the cert from my XCode to verify and decode a transactionReceipt I get from a purchase in the simulator against a StoreKit config I synced down from the App Store.  Can this be done?  I tried providing the cert and I couldn't get the receipt to verify/validate:


```import { SignedDataVerifier } from "@apple/app-store-server-library"
import { Environment } from "@apple/app-store-server-library"

const fs = require('fs');

function loadCAs() {
    return [
        fs.readFileSync('./StoreKitTestCertificate.cer'),
    ];
}

const bundleId = process.env.APPLE_APP_BUNDLE_ID!
const cas: Buffer[] = loadCAs() 
const environment = Environment.SANDBOX
const enableOnlineChecks = false ; // 0 docs on what this does and it was true in the example

console.log(bundleId)
const verifier = new SignedDataVerifier(cas, enableOnlineChecks, environment, bundleId)

const doit = async function () {
    try {
        const receipt = process.argv[2];  // Passing the receipt on the cmd line
        console.log("receipt", receipt);
        const trans = await verifier.verifyAndDecodeTransaction(receipt);
        console.log(trans)
    } catch (e) {
        console.error(e)
    }
}

doit();```

I get an exception as if the receipt is some other data/format than is expected:

```VerificationException [Error]
    at SignedDataVerifier.verifyJWT (/Users/ericbloch/repos/notewize-web/node_modules/@apple/app-store-server-library/jws_verification.ts:175:17)
    at SignedDataVerifier.verifyAndDecodeTransaction (/Users/ericbloch/repos/notewize-web/node_modules/@apple/app-store-server-library/jws_verification.ts:70:67)
    ... 6 lines matching cause stack trace ...
    at doit (/Users/ericbloch/repos/notewize-web/store-tools/verification.ts:58:12)
    at Object.<anonymous> (/Users/ericbloch/repos/notewize-web/store-tools/verification.ts:36:1) {
  status: 1,
  cause: TypeError: Cannot read properties of null (reading 'originalTransactionId')
      at JWSTransactionDecodedPayloadValidator.validate (/Users/ericbloch/repos/notewize-web/node_modules/@apple/app-store-server-library/models/JWSTransactionDecodedPayload.ts:213:24)
      at SignedDataVerifier.verifyJWT (/Users/ericbloch/repos/notewize-web/node_modules/@apple/app-store-server-library/jws_verification.ts:140:24)
      at SignedDataVerifier.verifyAndDecodeTransaction (/Users/ericbloch/repos/notewize-web/node_modules/@apple/app-store-server-library/jws_verification.ts:70:67)
      at /Users/ericbloch/repos/notewize-web/store-tools/verification.ts:29:38
      at step (/Users/ericbloch/repos/notewize-web/store-tools/verification.ts:33:23)
      at Object.next (/Users/ericbloch/repos/notewize-web/store-tools/verification.ts:14:53)
      at /Users/ericbloch/repos/notewize-web/store-tools/verification.ts:8:71
      at new Promise (<anonymous>)
      at __awaiter (/Users/ericbloch/repos/notewize-web/store-tools/verification.ts:4:12)
      at doit (/Users/ericbloch/repos/notewize-web/store-tools/verification.ts:58:12)
}
```

For what it's worth, I got the receipt from a purchase in a sim against my storekit config (using react-native-iap if that matters, but lmk).

Thanks for any help!

**Comment by alexanderjordanbaker** [comment]
You're probably looking for `Environment.XCODE` not `Environment.SANDBOX` as Xcode is used when testing via Xcode without the Sandbox environment that connects to the App Store. enableOnlineChecks enables checking for revocation on the certificates, which requires making an OCSP (RFC 2560) call to check the revocation status. This is documented in https://developer.apple.com/videos/play/wwdc2023/10143/. For Xcode testing that doesn't matter as the certificates you're working with are generated locally and certificate validation is skipped for the Xcode environment.

However, looking at this receipt, this is not an AppTransaction or signed transaction that the library could verify directly. This is an App Receipt from Original Storekit (https://developer.apple.com/documentation/storekit/in-app_purchase/original_api_for_in-app_purchase/validating_receipts_with_the_app_store). If you are unable to use StoreKit 2 for some reason, which provides the newer AppTransaction (https://developer.apple.com/documentation/storekit/apptransaction) and can be verified with the SignedDataVerifier, you can see an example from the README for how to work with legacy app receipts. A snippet is provided below.
`const appReceipt = "MI..."
const receiptUtil = new ReceiptUtility()
const transactionId = receiptUtil.extractTransactionIdFromAppReceipt(appReceipt)`

**Comment by eedeebee** [comment]
Thanks @alexanderjordanbaker ! I configured react-native-iap to use `StoreKit2` (forced my app to iOS 15.0 and later) and with `Environment.XCode `and my cert, I can use `SignedDataVerifier` !

**Comment by eedeebee** [comment]
I guess my original question stands though - do I need to verify the receipt still or just look up a transaction info to see if it matches what I think it should?

**Comment by alexanderjordanbaker** [comment]
@eedeebee If you verify the signed data with the SignedDataVerifier, you don't need to do anything else to verify the transaction.

**Comment by eedeebee** [comment]
Could you provide docs on what `enableOnlineChecks` does?
