### ISSUE TITLE
ResponseBodyV2DecodedPayload is missing the externalPurchaseToken

### ISSUE THREAD

**Issue by rodrigoborgesdeoliveira** [apple/app-store-server-library-node#98]
The [ResponseBodyV2DecodedPayload](https://github.com/apple/app-store-server-library-node/blob/796c8829b7a97286dc104c6611070980f70a68cd/models/ResponseBodyV2DecodedPayload.ts#L15C18-L15C46) is missing the [externalPurchaseToken](https://developer.apple.com/documentation/appstoreservernotifications/externalpurchasetoken) object mentioned in the [responseBodyV2DecodedPayload docs](https://developer.apple.com/documentation/appstoreservernotifications/responsebodyv2decodedpayload).

**Comment by alexanderjordanbaker** [comment]
Covered in PR https://github.com/apple/app-store-server-library-node/pull/107
